# Alt + Arrow keys பயன்படுத்தி விண்டோக்களை எளிதாக மாற்ற (இது 100% வேலை செய்யும்)
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# Fn + 4 (வேலை செய்ததால் அதை அப்படியே வைத்துக்கொள்ளலாம்)
bind -n F4 kill-session -t archide
